# -*- coding: utf-8 -*-
"""project1_chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3OR4VeCzokBLLmhDBl_dThg6i_3XQrR
"""

# project1_chatbot.py
# AI Chatbot using OpenAI API + LangChain (works in Colab)
# Install: pip install openai langchain

from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

# Set your API key before running
os.environ["OPENAI_API_KEY"] = "your_api_key_here"

def ai_chatbot():
    llm = OpenAI(temperature=0.7)
    prompt = PromptTemplate(
        input_variables=["question"],
        template="You are a helpful AI assistant. Answer the following: {question}"
    )
    chain = LLMChain(llm=llm, prompt=prompt)

    while True:
        question = input("Ask something (type 'exit' to quit): ")
        if question.lower() == "exit":
            break
        print("AI:", chain.run(question))

if __name__ == "__main__":
    ai_chatbot()